site_name: Sistema de Intenção de Matrícula

theme:
  name: material
  language: pt-BR

plugins:
  - search
  - include-markdown

nav:
  - Início: index.md

  - Requisitos:
      - Requisitos Funcionais: Requisitos/Requisitos_funcionais.md
      - Requisitos Não Funcionais: Requisitos/Requisitos_nao_funcionais.md

  - Épicos e Histórias:
      - Autenticação e Acesso ao Sistema: epicos_e_historias_de_usuarios/EP01_Autenticação_e_Acesso.md
      - Cadastro e Gestão de Perfil: epicos_e_historias_de_usuarios/EP02_Cadastro_e_Gestão.md
      - Diferenciação de Papéis: epicos_e_historias_de_usuarios/EP03_Diferenciação_de_Papéis.md
      - Captação de Interesse Aluno: epicos_e_historias_de_usuarios/EP04_Captacao_de_interesse_alunos.md
      - Inteligência de validação: epicos_e_historias_de_usuarios/EP05_Inteligencia_e_validacao.md
      - Planejamento e Coordenação Acadêmica: epicos_e_historias_de_usuarios/EP06_Planejamento_e_Coordenação Acadêmica.md
      - Análise e Monitoramento das Pré-Matrículas: epicos_e_historias_de_usuarios/EP07_Analise_e_Monitoramento_das_Pre-Matreculas.md


  - Histórico:
      - Divisão de Tarefas da Equipe: Historico/historico.md
      
  - Modelos:
      - Modelo Conceitual: Modelos/modelo_conceitual.md
      - Modelo Físico: Modelos/modelo_fisico.md
