site_name: Sistema de Intenção de Matrícula

theme:
  name: material
  language: pt-BR

plugins:
  - search
  - include-markdown

nav:
  - Início: index.md

  - Requisitos:
      - Requisitos Funcionais: Requisitos/Requisitos_funcionais.md
      - Requisitos Não Funcionais: Requisitos/Requisitos_nao_funcionais.md

  - Épicos e Histórias:
      - Captação de Interesse Aluno: epicos_e_historias_de_usuarios/EP04_Captacao_de_interesse_alunos.md
      - Inteligência de validação: epicos_e_historias_de_usuarios/EP05_Inteligencia_e_validacao.md
