site_name: Sistema de Intenção de Matrícula

theme:
  name: material
  language: pt-BR

plugins:
  - search
  - include-markdown

nav:
  - Início: index.md

  - Requisitos:
      - Requisitos Funcionais: Requisitos/Requisitos_Funcionais.md
      - Requisitos Não Funcionais: Requisitos/Requisitos_nao_funcionais.md

  - Épicos e Histórias:
      - Captação de Interesse Aluno: Epicos_e_historias_de_usuarios/Captação_de_interesse_Aluno.md
