name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-include-markdown-plugin

      - name: Deploy GitHub Pages
        run: mkdocs gh-deploy --force
